### ISSUE TITLE
sqlite3 python module cannot be imported in Gaffer Windows

### ISSUE THREAD

**Issue by diegogarciahuerta** [hypothetical-inc/gaffer#21]
**Version**: Gaffer 0.57.3.0-windows
**Third-party tools:** None
**Third-party modules:** None

### Description ###

*sqlite3* module cannot be imported within this version of Gaffer in Windows. I believe half of the distribution files for this module might be missing, ie. _sqlite3

Would anyone mind checking if this happens to you too, please ?

I've tried to add the one distributed with the original version of python that matches the one in Gaffer, but it must be compiled differently because it does not like it, (complains about issues with DLL not being able to be loaded.) 
I've also checked with a few previous versions of Windows Gaffer but had no luck either.

I'm taking a look at what would take to integrate Shotgun with Gaffer and this is the first roadblock I've encountered, so if you could help that would be great.

### Steps to reproduce ###

Try to import sqlite3 within the Gaffer python editor:
```
import sqlite3
```

### Debug log ###

<details>
<summary>Click to Expand</summary><p>

```
import sqlite3
ImportError : line 1 : No module named _sqlite3 
  File "C:\Program Files\gaffer-0.57.3.0-windows\lib64\sqlite3\__init__.py", line 24, in <module>
    from dbapi2 import *
  File "C:\Program Files\gaffer-0.57.3.0-windows\lib64\sqlite3\dbapi2.py", line 28, in <module>
    from _sqlite3 import *
```

</p>
</details>

**Comment by ericmehl** [comment]
Hi Diego, sounds like a great project! Shotgun support would be great to have from within Gaffer.

Right now we're not building sqlite into the Python build. Our custom build of Python includes the sqlite3 module, but without the sqlite sources when it's built it won't create _sqlite3 as you've run into.

That's the case with the official Linux builds as well. I think it's based on the desire to not include dependencies that are not strictly needed for Gaffer itself, especially since there are already so many to keep track of.

One option you can try is installing sqlite to a dedicated directory and using GAFFER_EXTENSION_PATHS to include it in Gaffer.

I tried installing it using pip but it's a number of years old now and it wasn't building with a modern MSVC. But have a look at this discussion - it might help you get it built from sources: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pysqlite

If you go down this route you need to do a couple things in addition to the pysqlite build itself:
1. Gaffer looks for python modules (.pyd files) in a subdirectory called `python` and DLLs in either `bin` or `lib`, you may need to rearrange the default installation somewhat.
3. Before launching gaffer.bat set the environment variable `set GAFFER_EXTENSION_PATHS=C:\gaffer_extensions` (with whatever directory you built the module in place of `gaffer_extensions`). You can have multiple extension paths separated by a semi-colon like a regular Windows PATH

So not the easiest process but probably can work. The GafferHQ release is being updated to Python3 so this might get easier with that update as it looks like pysqlite for Python 3 is actively maintained. Though I don't know when they expect to have that update made, it's a pretty big one I imagine.

**Comment by diegogarciahuerta** [comment]
Hi Eric,

Many thanks for the detailed explanation, I'm developing the engine precisely to get more familiarized with the Gaffer API, so I'm not in a big rush, but I will give pysqlite/python2.x a try and see what happens.   
Knowing that Gaffer only builds with the dependencies it needs is also good to know, I might encounter other modules required by Shotgun Toolkit , so perhaps I should adventure myself to compile Gaffer Windows itself too.

I will report back when I have something tangible,

Thanks again!
