### ISSUE TITLE
Missing open folder button on aiImage (Windows)

### ISSUE THREAD

**Issue by bintangsenja** [hypothetical-inc/gaffer#5]
I've downloaded gaffer-0.54.1.0-windows, but aiImage (Arnold Image) seem not having any button for opening the image, I need to manually type in and change the backslash to forward slash. Thanks
![image](https://user-images.githubusercontent.com/18478977/65834083-8f4a6280-e301-11e9-8c94-20e1a814b7cf.png)

**Comment by ericmehl** [comment]
Hi @bintangsenja - this should be fixed in the latest release, [0.55.1.0](https://github.com/hypothetical-inc/gaffer/releases/tag/0.55.1.0)

Give that a try and see if it works for you. The same problem that prevented the file picker button also created extra warnings when rendering which should be better now as well.

Thanks for flagging it! It pointed me in the right direction to solve some random issues which make Gaffer on Windows better.

I'm closing this for now, but please reopen it or create a new issue if the new 0.55.1.0 release doesn't solve it for you.
