### ISSUE TITLE
Gaffer crashes when clicking on OSL nodes (Windows)

### ISSUE THREAD

**Issue by BigRoy** [hypothetical-inc/gaffer#7]
**Version**: [Gaffer Windows 0.54.1.0-beta](https://github.com/hypothetical-inc/gaffer/releases/tag/0.54.1.0)

### Description ###

It seems that OSL code runs fine on Windows however displaying some of the nodes themselves seem to crash Gaffer. This only happens if there's at least one Viewer that is trying to display it. If you pin the viewer to another node you can tweak the settings on the OSL node just fine.

I believe OSL being broken on Windows has been mentioned before but this Issue is to make sure it's tracked. Plus it also describes that the OSL code actually *does* trigger correctly. It's just that the viewer crashes when active on the OSL node itself.

### Steps to reproduce ###

1. Download the example OSL file shared [here](https://groups.google.com/forum/#!msg/gaffer-dev/D7AY4Wl4Zrs/VEl8oGLlAwAJ).
2. Press 2 on the keyboard to go to Bookmark 2.
3. Click on `DeletePrimitiveVariables` node, see how it displays geometry just fine.
4. Click on `AddVector` and it crashes. (This is an `oslAddVector` node.)

Note now when you pin the Viewer to `DeletePrimitiveVariables` (or `OSLObject`) how you can now click on those node just fine and change attributes. For example click on `OSLCode` on far left and change the "Width" value there.

Note also how Bookmark 1 (resulting in a 2D image also works).

### Debug log ###

Unfortunately I'm not getting any visible output because Gaffer instantly disappears. All I see in command line is the following:

<details>
<summary>Click to Expand</summary><p>

```
C:\gaffer-0.54.1.0-windows\bin>if -1073740940 NEQ 0 (
echo "Error(s) running Gaffer"
 exit /b -1073740940
)
"Error(s) running Gaffer"
```
</p>
</details>

**Comment by ericmehl** [comment]
Do you happen to be using Appleseed for previews? That is known to crash right now. I'll have a look at the OSL you shared and give it a try with my demo Arnold setup.

I also want to check on how Gaffer behaves with no rendering engine, including Appleseed. I'm unlikely to have the time to debug the crashing of Appleseed so will need to rely on their devs or someone else to take up that task.

**Comment by BigRoy** [comment]
> Do you happen to be using Appleseed for previews?

Actually, good question. But I believe it's reproducible in an empty scene too when creating these osl nodes. So I guess that means "no renderer"? I am not sure what the Viewport is trying to show when you are clicking those crashing osl nodes. (I was unable to test it on Linux to see what happens there)

If I recall correctly I was also able to get the example MacBeth chart scene to crash when selecting the `OSLCode` node. It's in the `Help > Examples ` menu somewhere.

**Comment by xtvjxk123456** [comment]
same issue on my pc.
-Gaffer Windows 0.54.1.0-beta
-arnold 5.4.0.0
(gaffer "oslcode" and arnold "aiOsl") cause gaffer crash

**Comment by xtvjxk123456** [comment]
i found something:
it will crash on select "oslcode" when loaded appleseed and arnold same time.
aiosl always crash.

**Comment by ericmehl** [comment]
Appleseed was causing lots of problems since it isn't working on Windows yet. Your best bet is to disable it by removing or commenting out the lines in gaffer.bat where it is loaded.

The latest [0.55.1.0 release](https://github.com/hypothetical-inc/gaffer/releases/tag/0.55.1.0) that I just put up does this and I think it will lead to a much better experience.

@BigRoy I think this will also fix your problem with certain OSL nodes working and others not. Depending on the type of OSL node, different viewers are used. Some are just 2d images - the OSLImage related nodes - and display fine because it is using 2d display. OSLObject nodes were working because that is evaluated on object primitives and displayed using the regular OpenGL display. Where the problems came up were shader related nodes like AddVector you pointed out. This attempts to use the renderer, Appleseed by default, to show the result of the shader code.

With Appleseed disabled you will get a black 2d image as a preview. Unfortunately this means working with OSL shaders requires Arnold now. But since Appleseed was crashing Gaffer entirely I think it's actually an improvement. The Arnold demo might be useful enough if you are doing shader previews - it leaves a watermark but as far as I can tell it's fully functional otherwise.

**Comment by ericmehl** [comment]
I'm going to close this since it's a known bug, but please reopen or create a new issue if you are continuing to have problems even with Appleseed disabled.
